
  
name: Build,Analyze,scan
on:
  push:
    branches:
      - main
jobs:
  build-analyze-scan:
    name: Build
    runs-on: suvo
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Build and analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: npm install
        run: sudo apt install nodejs npm -y
   
      - name: Trivy installation
        run: |
         sudo apt-get update && sudo apt-get install -y wget apt-transport-https gnupg lsb-release
         wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
         echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/trivy.list
         sudo apt-get update
         sudo apt-get install -y trivy
      - name: Trivy fs scan
        run: trivy fs --format table -o fs-report.json .
      - name: docker build and push
        run: |
          docker build -t game .
          docker tag game learnersubha/game:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME}} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push learnersubha/game:latest
        env:
          DOCKER_CLI_ACI: 1
      - name: image scan
        run: trivy image learnersubha/game:latest > scanimage.txt

  deploy: 
    needs: build-analyze-scan
    runs-on: suvo
    steps:
      - name: docker image pull
        run: docker pull learnersubha/game:latest

      - name: image scan
        run: trivy image learnersubha/game:latest > pullimage.txt

      - name: deploy to container
        run: docker run -d --name tic-tac-toe -p 3000:3000 learnersubha/game:latest
